### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by AlphaGaming**

### CODE REVIEW

**Comment by AlphaGaming** [comment]
Alex

**Comment by AlexFreedomMod** [comment]
Yes?

**Comment by AlphaGaming** [comment]
I am making a new mod account

**Comment by AlexFreedomMod** [comment]
Why?

**Comment by AlphaGaming** [comment]
Because the old one didn't compile

**Comment by AlphaGaming** [comment]
What's your skype

**Comment by AlexFreedomMod** [comment]
Why don't you try to fix it on this account then?

**Comment by AlphaGaming** [comment]
So we can talk about alexFreedomMod

**Comment by AlexFreedomMod** [comment]
Sorry, got to go. Dinner

**Comment by AlphaGaming** [comment]
I will add it to this account when I'm finished compiling everything

**Comment by AlexFreedomMod** [comment]
K.

**Pull request merged**
